const destinos = [
    {
        id: 10,
        url: '/destinos/europa',
        nombre: 'Europa',
        h1: 'Europa - Continente de Historia y Cultura',
        h2: 'Descubre la diversidad europea',
        video_mobile: '/images/Placeholder.png',
        video_desktop: '/images/Placeholder.png',
        experto_id: 1,
        consejo_experto: 'Europa ofrece una increíble diversidad cultural en distancias cortas',
        img: '/images/Placeholder.png',
        txt_search: 'Europa, cultura, historia, arte, arquitectura',
        meta_titulo: 'Europa - Tours por el continente histórico',
        meta_descripcion: 'Explora Europa con nuestros tours especializados',
        meta_keywords: 'Europa, turismo, cultura, historia, arte',
        mapa: '50.0755,14.4378',
        estado: 'Activo',
        nro_orden: 1,
        desde_precio: 1299.00
    },
    {
        id: 11,
        url: '/destinos/america-del-sur',
        nombre: 'América del Sur',
        h1: 'América del Sur - Naturaleza y Aventura',
        h2: 'Descubre la magia sudamericana',
        video_mobile: '/images/Placeholder.png',
        video_desktop: '/images/Placeholder.png',
        experto_id: 2,
        consejo_experto: 'Prepárate para paisajes únicos y culturas fascinantes',
        img: '/images/Placeholder.png',
        txt_search: 'América del Sur, naturaleza, aventura, cultura',
        meta_titulo: 'América del Sur - Tours de aventura y naturaleza',
        meta_descripcion: 'Explora América del Sur con expertos locales',
        meta_keywords: 'América del Sur, aventura, naturaleza, turismo',
        mapa: '-14.2350,-51.9253',
        estado: 'Activo',
        nro_orden: 2,
        desde_precio: 1599.00
    },
    {
        id: 1,
        url: '/destinos/francia',
        nombre: 'Francia',
        h1: 'Francia - País del Arte y la Elegancia',
        h2: 'Descubre la magia francesa',
        video_mobile: '/images/Placeholder.png',
        video_desktop: '/images/Placeholder.png',
        experto_id: 2,
        consejo_experto: 'Francia combina arte, gastronomía y paisajes únicos',
        img: '/images/Placeholder.png',
        txt_search: 'Francia, París, Torre Eiffel, Louvre, gastronomía',
        meta_titulo: 'Francia - Guía completa del país del arte',
        meta_descripcion: 'Descubre Francia con nuestros tours especializados',
        meta_keywords: 'Francia, París, Torre Eiffel, Louvre, turismo',
        mapa: '46.2276,2.2137',
        estado: 'Activo',
        nro_orden: 3,
        desde_precio: 899.00,
        regionId: 10
    },
    {
        id: 2,
        url: '/destinos/reino-unido',
        nombre: 'Reino Unido',
        h1: 'Reino Unido - Tradición y Modernidad',
        h2: 'Tradición y modernidad en perfecta armonía',
        video_mobile: '/images/Placeholder.png',
        video_desktop: '/images/Placeholder.png',
        experto_id: 1,
        consejo_experto: 'No olvides llevar paraguas, el clima puede cambiar rápidamente',
        img: '/images/Placeholder.png',
        txt_search: 'Reino Unido, Londres, Big Ben, Buckingham Palace, Támesis',
        meta_titulo: 'Reino Unido - Tours por las islas británicas',
        meta_descripcion: 'Explora Reino Unido con guías expertos locales',
        meta_keywords: 'Reino Unido, Londres, Big Ben, Buckingham, turismo',
        mapa: '55.3781,-3.4360',
        estado: 'Activo',
        nro_orden: 4,
        desde_precio: 1199.00,
        regionId: 10
    },
    {
        id: 3,
        url: '/destinos/italia',
        nombre: 'Italia',
        h1: 'Italia - La Cuna del Arte',
        h2: 'Donde cada piedra cuenta una historia',
        video_mobile: '/images/Placeholder.png',
        video_desktop: '/images/Placeholder.png',
        experto_id: 3,
        consejo_experto: 'Reserva la entrada al Vaticano con anticipación para evitar colas',
        img: '/images/Placeholder.png',
        txt_search: 'Italia, Roma, Coliseo, Vaticano, Fontana di Trevi',
        meta_titulo: 'Italia - Descubre la cuna del arte',
        meta_descripcion: 'Tours culturales por la histórica Italia',
        meta_keywords: 'Italia, Roma, Coliseo, Vaticano, historia',
        mapa: '41.8719,12.5674',
        estado: 'Activo',
        nro_orden: 5,
        desde_precio: 759.00,
        regionId: 10
    },
    {
        id: 4,
        url: '/destinos/españa',
        nombre: 'España',
        h1: 'España - Pasión y Tradición',
        h2: 'Arte, cultura y gastronomía ibérica',
        video_mobile: '/images/Placeholder.png',
        video_desktop: '/images/Placeholder.png',
        experto_id: 4,
        consejo_experto: 'Disfruta de las tapas y la siesta española',
        img: '/images/Placeholder.png',
        txt_search: 'España, Madrid, Barcelona, Prado, Retiro, Gran Vía',
        meta_titulo: 'España - Tours por la península ibérica',
        meta_descripcion: 'Descubre España con expertos locales',
        meta_keywords: 'España, Madrid, Barcelona, Prado, Retiro, tapas',
        mapa: '40.4637,-3.7492',
        estado: 'Activo',
        nro_orden: 6,
        desde_precio: 649.00,
        regionId: 10
    },
    {
        id: 5,
        url: '/destinos/argentina',
        nombre: 'Argentina',
        h1: 'Argentina - Tierra de Pasión',
        h2: 'Tango, asado y paisajes infinitos',
        video_mobile: '/images/Placeholder.png',
        video_desktop: '/images/Placeholder.png',
        experto_id: 1,
        consejo_experto: 'Prueba un buen asado argentino y aprende a bailar tango',
        img: '/images/Placeholder.png',
        txt_search: 'Argentina, Buenos Aires, tango, Patagonia, Mendoza',
        meta_titulo: 'Argentina - Tierra de tango y paisajes',
        meta_descripcion: 'Tours por Argentina con guías locales',
        meta_keywords: 'Argentina, Buenos Aires, tango, Patagonia, turismo',
        mapa: '-38.4161,-63.6167',
        estado: 'Activo',
        nro_orden: 7,
        desde_precio: 1199.00,
        regionId: 11
    }
]

export default destinos
