const destinos = [
    {
        id: 1,
        url: '/destinos/paris',
        nombre: 'París',
        h1: 'París - La Ciudad de la Luz',
        h2: 'Descubre la magia parisina',
        video_mobile: '/videos/paris-mobile.mp4',
        video_desktop: '/videos/paris-desktop.mp4',
        experto_id: 2,
        consejo_experto: 'Visita la Torre Eiffel al atardecer para las mejores fotos',
        img: '/images/destinos/paris.jpg',
        txt_search: 'París, ciudad del amor, Torre Eiffel, Louvre',
        meta_titulo: 'París - Guía completa de la Ciudad de la Luz',
        meta_descripcion: 'Descubre París con nuestros tours especializados',
        meta_keywords: 'París, Francia, Torre Eiffel, Louvre, turismo',
        mapa: '48.8566,2.3522',
        estado: 'activo',
        nro_orden: 1,
        desde_precio: 899.00
    },
    {
        id: 2,
        url: '/destinos/londres',
        nombre: 'Londres',
        h1: 'Londres - Capital del Reino Unido',
        h2: 'Tradición y modernidad en perfecta armonía',
        video_mobile: '/videos/londres-mobile.mp4',
        video_desktop: '/videos/londres-desktop.mp4',
        experto_id: 1,
        consejo_experto: 'No olvides llevar paraguas, el clima puede cambiar rápidamente',
        img: '/images/destinos/londres.jpg',
        txt_search: 'Londres, Big Ben, Buckingham Palace, Támesis',
        meta_titulo: 'Londres - Tours por la capital británica',
        meta_descripcion: 'Explora Londres con guías expertos locales',
        meta_keywords: 'Londres, Reino Unido, Big Ben, Buckingham, turismo',
        mapa: '51.5074,-0.1278',
        estado: 'activo',
        nro_orden: 2,
        desde_precio: 1199.00
    },
    {
        id: 3,
        url: '/destinos/roma',
        nombre: 'Roma',
        h1: 'Roma - La Ciudad Eterna',
        h2: 'Donde cada piedra cuenta una historia',
        video_mobile: '/videos/roma-mobile.mp4',
        video_desktop: '/videos/roma-desktop.mp4',
        experto_id: 3,
        consejo_experto: 'Reserva la entrada al Vaticano con anticipación para evitar colas',
        img: '/images/destinos/roma.jpg',
        txt_search: 'Roma, Coliseo, Vaticano, Fontana di Trevi',
        meta_titulo: 'Roma - Descubre la Ciudad Eterna',
        meta_descripcion: 'Tours culturales por la histórica Roma',
        meta_keywords: 'Roma, Italia, Coliseo, Vaticano, historia',
        mapa: '41.9028,12.4964',
        estado: 'activo',
        nro_orden: 3,
        desde_precio: 759.00
    },
    {
        id: 4,
        url: '/destinos/madrid',
        nombre: 'Madrid',
        h1: 'Madrid - Capital de España',
        h2: 'Arte, cultura y gastronomía en el corazón de España',
        video_mobile: '/videos/madrid-mobile.mp4',
        video_desktop: '/videos/madrid-desktop.mp4',
        experto_id: 4,
        consejo_experto: 'Disfruta de las tapas en el barrio de La Latina por la tarde',
        img: '/images/destinos/madrid.jpg',
        txt_search: 'Madrid, Prado, Retiro, Gran Vía',
        meta_titulo: 'Madrid - Tours por la capital española',
        meta_descripcion: 'Descubre Madrid con expertos locales',
        meta_keywords: 'Madrid, España, Prado, Retiro, tapas',
        mapa: '40.4168,-3.7038',
        estado: 'activo',
        nro_orden: 4,
        desde_precio: 649.00
    },
    {
        id: 5,
        url: '/destinos/barcelona',
        nombre: 'Barcelona',
        h1: 'Barcelona - Perla del Mediterráneo',
        h2: 'Modernismo y tradición mediterránea',
        video_mobile: '/videos/barcelona-mobile.mp4',
        video_desktop: '/videos/barcelona-desktop.mp4',
        experto_id: 1,
        consejo_experto: 'Visita la Sagrada Familia temprano en la mañana para mejores fotos',
        img: '/images/destinos/barcelona.jpg',
        txt_search: 'Barcelona, Gaudí, Sagrada Familia, Park Güell',
        meta_titulo: 'Barcelona - Ciudad modernista de Gaudí',
        meta_descripcion: 'Tours arquitectónicos por Barcelona',
        meta_keywords: 'Barcelona, España, Gaudí, Sagrada Familia, modernismo',
        mapa: '41.3851,2.1734',
        estado: 'activo',
        nro_orden: 5,
        desde_precio: 699.00
    }
]

export default destinos
