const productos = [
    {
        id: 1,
        nombreprod: "Tour Machu Picchu Clásico",
        h1: "Descubre Machu Picchu con Tour Experto",
        img: "/images/Placeholder.png",
        img_mobile: "/images/Placeholder.png",
        video_mapa_mobile: "/videos/machu-picchu-mobile.mp4",
        video_mapa_desktop: "/videos/machu-picchu-desktop.mp4",
        podcast: "/audio/machu-picchu-podcast.mp3",
        codigo_newton: 201,
        url: "/tours/machu-picchu-clasico",
        cantidad_estrellas: 5,
        cantidadAport: 150,
        consejo_experto: "La mejor época para visitar es entre mayo y septiembre",
        expertoId: 1,
        meta_titulo: "Tour Machu Picchu Clásico - Tour Experto",
        meta_descripcion: "Visita la ciudadela inca más famosa del mundo con nuestros expertos",
        estado: "Activo",
        precio_total: 1299.00
    },
    {
        id: 2,
        nombreprod: "Experiencia Iguazú Premium",
        h1: "Cataratas del Iguazú como nunca las viste",
        img: "/images/Placeholder.png",
        img_mobile: "/images/Placeholder.png",
        video_mapa_mobile: "/videos/iguazu-mobile.mp4",
        video_mapa_desktop: "/videos/iguazu-desktop.mp4",
        podcast: "/audio/iguazu-podcast.mp3",
        codigo_newton: 202,
        url: "/tours/iguazu-premium",
        cantidad_estrellas: 5,
        cantidadAport: 89,
        consejo_experto: "Lleva impermeable y cámara con protección",
        expertoId: 2,
        meta_titulo: "Cataratas Iguazú Premium - Tour Experto",
        meta_descripcion: "Experiencia premium en las cataratas más impresionantes de Sudamérica",
        estado: "Activo",
        precio_total: 899.00
    },
    {
        id: 3,
        nombreprod: "Safari Patagónico",
        h1: "Aventura en la Patagonia Argentina",
        img: "/images/Placeholder.png",
        img_mobile: "/images/Placeholder.png",
        video_mapa_mobile: "/videos/patagonia-mobile.mp4",
        video_mapa_desktop: "/videos/patagonia-desktop.mp4",
        podcast: "/audio/patagonia-podcast.mp3",
        codigo_newton: 203,
        url: "/tours/safari-patagonico",
        cantidad_estrellas: 4,
        cantidadAport: 45,
        consejo_experto: "Época ideal: noviembre a marzo para mejor clima",
        expertoId: 3,
        meta_titulo: "Safari Patagónico - Tour Experto",
        meta_descripcion: "Descubre la vida salvaje y paisajes únicos de la Patagonia",
        estado: "Activo",
        precio_total: 1599.00
    },
    {
        id: 4,
        nombreprod: "Tour Machu Picchu Clásico",
        h1: "La Ciudad Perdida de los Incas",
        img: "/images/Placeholder.png",
        img_mobile: "/images/Placeholder.png",
        video_mapa_mobile: "/images/Placeholder.png",
        video_mapa_desktop: "/images/Placeholder.png",
        podcast: "/audio/machupicchu-podcast.mp3",
        codigo_newton: 404,
        url: "/tours/machu-picchu-clasico",
        cantidad_estrellas: 5,
        cantidadAport: 156,
        consejo_experto: "Reserva con tiempo, las entradas son limitadas",
        expertoId: 1,
        meta_titulo: "Machu Picchu Clásico - Tour Experto",
        meta_descripcion: "Descubre la maravilla del mundo con nuestros guías especializados",
        estado: "Activo",
        precio_total: 1299.00
    },
    {
        id: 5,
        nombreprod: "Europa Medieval - Castillos y Catedrales",
        h1: "Viaje por la Europa Medieval",
        img: "/images/Placeholder.png",
        img_mobile: "/images/Placeholder.png",
        video_mapa_mobile: "/images/Placeholder.png",
        video_mapa_desktop: "/images/Placeholder.png",
        podcast: "/audio/europa-medieval-podcast.mp3",
        codigo_newton: 505,
        url: "/tours/europa-medieval",
        cantidad_estrellas: 4,
        cantidadAport: 67,
        consejo_experto: "Lleva calzado cómodo para caminar en adoquines",
        expertoId: 2,
        meta_titulo: "Europa Medieval - Tour Experto",
        meta_descripcion: "Explora castillos, catedrales y ciudades medievales de Europa",
        estado: "Activo",
        precio_total: 2199.00
    }
]

export default productos
