const categorias = [
    {
        id: 1,
        nombre: 'Aventura',
        descripcion: 'Viajes llenos de adrenalina y actividades extremas',
        h1: 'Aventura y Deportes Extremos',
        h2: 'Vive la emoción al máximo',
        meta_titulo: 'Tours de Aventura - Experiencias Extremas',
        meta_descripcion: 'Descubre los mejores tours de aventura y deportes extremos',
        meta_keywords: 'aventura, deportes extremos, adrenalina',
        icono: '/images/Placeholder.png',
        coordenadas_icono: '100,200',
        coordenadas_icono_hover: '120,220',
        nro_orden: 1,
        img_carousel: '/images/Placeholder.png',
        img_search: '/images/Placeholder.png',
        video_mobile: '/images/Placeholder.png',
        video_desktop: '/images/Placeholder.png',
        estado: 'Activo',
        codigo_newton: 1,
        idExperto: 1,
        consejo_experto: 'Siempre verifica el equipo de seguridad antes de cualquier actividad',
        url: '/categorias/aventura'
    },
    {
        id: 2,
        nombre: 'Cultura',
        descripcion: 'Sumérgete en la historia y tradiciones locales',
        h1: 'Turismo Cultural',
        h2: 'Descubre tradiciones milenarias',
        meta_titulo: 'Tours Culturales - Historia y Tradiciones',
        meta_descripcion: 'Explora la riqueza cultural de cada destino',
        meta_keywords: 'cultura, historia, tradiciones, museos',
        icono: '/images/Placeholder.png',
        coordenadas_icono: '200,300',
        coordenadas_icono_hover: '220,320',
        nro_orden: 2,
        img_carousel: '/images/Placeholder.png',
        img_search: '/images/Placeholder.png',
        video_mobile: '/images/Placeholder.png',
        video_desktop: '/images/Placeholder.png',
        estado: 'Activo',
        codigo_newton: 2,
        idExperto: 2,
        consejo_experto: 'Investiga la historia del lugar antes de visitarlo para una mejor experiencia',
        url: '/categorias/cultura'
    },
    {
        id: 3,
        nombre: 'Relax',
        descripcion: 'Experiencias para desconectar y renovar energías',
        h1: 'Turismo de Bienestar',
        h2: 'Relájate y renuévate',
        meta_titulo: 'Tours de Relax - Bienestar y Spa',
        meta_descripcion: 'Los mejores destinos para relajarse y desconectar',
        meta_keywords: 'relax, spa, bienestar, descanso',
        icono: '/images/Placeholder.png',
        coordenadas_icono: '300,400',
        coordenadas_icono_hover: '320,420',
        nro_orden: 3,
        img_carousel: '/images/Placeholder.png',
        img_search: '/images/Placeholder.png',
        video_mobile: '/images/Placeholder.png',
        video_desktop: '/images/Placeholder.png',
        estado: 'Activo',
        codigo_newton: 3,
        idExperto: 3,
        consejo_experto: 'Reserva tratamientos de spa con anticipación durante temporada alta',
        url: '/categorias/relax'
    },
    {
        id: 4,
        nombre: 'Gastronómico',
        descripcion: 'Descubre los sabores únicos de cada destino',
        h1: 'Turismo Gastronómico',
        h2: 'Saborea el mundo',
        meta_titulo: 'Tours Gastronómicos - Sabores del Mundo',
        meta_descripcion: 'Experiencias culinarias únicas en cada destino',
        meta_keywords: 'gastronomía, comida, restaurantes, sabores',
        icono: '/images/Placeholder.png',
        coordenadas_icono: '400,500',
        coordenadas_icono_hover: '420,520',
        nro_orden: 4,
        img_carousel: '/images/Placeholder.png',
        img_search: '/images/Placeholder.png',
        video_mobile: '/images/Placeholder.png',
        video_desktop: '/images/Placeholder.png',
        estado: 'Activo',
        codigo_newton: 4,
        idExperto: 4,
        consejo_experto: 'Prueba siempre los platos típicos de la región que visites',
        url: '/categorias/gastronomico'
    },
    {
        id: 5,
        nombre: 'Histórico',
        descripcion: 'Recorre los lugares que marcaron la historia',
        h1: 'Turismo Histórico',
        h2: 'Camina por la historia',
        meta_titulo: 'Tours Históricos - Patrimonio Mundial',
        meta_descripcion: 'Visita los sitios históricos más importantes del mundo',
        meta_keywords: 'historia, patrimonio, monumentos, arqueología',
        icono: '/images/Placeholder.png',
        coordenadas_icono: '500,600',
        coordenadas_icono_hover: '520,620',
        nro_orden: 5,
        img_carousel: '/images/Placeholder.png',
        img_search: '/images/Placeholder.png',
        video_mobile: '/images/Placeholder.png',
        video_desktop: '/images/Placeholder.png',
        estado: 'Activo',
        codigo_newton: 5,
        idExperto: 1,
        consejo_experto: 'Contrata guías locales para conocer las historias no documentadas',
        url: '/categorias/historico'
    }
]

export default categorias
